nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

logFilters:
    - pattern: 'eslint-plugin-deprecation'
      level: discard
    - pattern: 'eslint-plugin-istanbul'
      level: discard
    - pattern: 'eslint-plugin-misc'
      level: discard
