name: Continous Integration

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Continous Integration
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn
            - name: Lint validation
              run: yarn lint
            - name: Module compilation and build
              run: yarn build
            - name: Test and coverage
              run: yarn vitest run --coverage
            - name: SonarCloud Scan
              uses: SonarSource/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Chromatic build
              uses: chromaui/action@latest
              with:
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                token: ${{ secrets.GITHUB_TOKEN }}
